import React from "react"
const orders = {
  count: 9,
  data: [
    {
      order_id: '100',
      customer_id: "101",
      cust_name: "ABC",
      cust_status: "placed",
      city: "chennai",
      delivery_agent_id: "D01",
      DA_vehical_no: "BR1Q1995",
      retailer_id: "R01",
      paid_amount: "100",
      assigned_to: "swiggy",
      retailer_name: "Raju",
      date_and_time: "01/02/2020"
    },
    {
      order_id: '200',
      customer_id: "102",
      cust_name: "XYZ",
      cust_status: "cancelled",
      city: "chennai",
      delivery_agent_id: "D02",
      DA_vehical_no: "BR1Q1994",
      retailer_id: "R02",
      paid_amount: "456",
      assigned_to: "swiggy",
      retailer_name: "Raju",
      date_and_time: "01/02/2020"
    },
    {
      order_id: '300',
      customer_id: "103",
      cust_name: "PQR",
      cust_status: "placed",
      city: "chennai",
      delivery_agent_id: "D03",
      DA_vehical_no: "BR1Q19955",
      retailer_id: "R03",
      paid_amount: "99",
      assigned_to: "swiggy",
      retailer_name: "Raju",
      date_and_time: "01/02/2020"
    },
    {
      order_id: '400',
      customer_id: "101",
      cust_name: "ABC",
      cust_status: "placed",
      city: "chennai",
      delivery_agent_id: "D01",
      DA_vehical_no: "BR1Q1995",
      retailer_id: "R01",
      paid_amount: "100",
      assigned_to: "swiggy",
      retailer_name: "Raju",
      date_and_time: "01/02/2020"
    },
    {
      order_id: '500',
      customer_id: "102",
      cust_name: "XYZ",
      cust_status: "cancelled",
      city: "chennai",
      delivery_agent_id: "D02",
      DA_vehical_no: "BR1Q1994",
      retailer_id: "R02",
      paid_amount: "456",
      assigned_to: "swiggy",
      retailer_name: "Raju",
      date_and_time: "01/02/2020"
    },
    {
      order_id: '600',
      customer_id: "103",
      cust_name: "PQR",
      cust_status: "placed",
      city: "chennai",
      delivery_agent_id: "D03",
      DA_vehical_no: "BR1Q19955",
      retailer_id: "R03",
      paid_amount: "99",
      assigned_to: "swiggy",
      retailer_name: "Raju",
      date_and_time: "01/02/2020"
    },
    {
      order_id: '400',
      customer_id: "101",
      cust_name: "ABC",
      cust_status: "placed",
      city: "chennai",
      delivery_agent_id: "D01",
      DA_vehical_no: "BR1Q1995",
      retailer_id: "R01",
      paid_amount: "100",
      assigned_to: "swiggy",
      retailer_name: "Raju",
      date_and_time: "01/02/2020"
    },
    {
      order_id: '500',
      customer_id: "102",
      cust_name: "XYZ",
      cust_status: "cancelled",
      city: "chennai",
      delivery_agent_id: "D02",
      DA_vehical_no: "BR1Q1994",
      retailer_id: "R02",
      paid_amount: "456",
      assigned_to: "swiggy",
      retailer_name: "Raju",
      date_and_time: "01/02/2020"
    },
    {
      order_id: '600',
      customer_id: "103",
      cust_name: "PQR",
      cust_status: "placed",
      city: "chennai",
      delivery_agent_id: "D03",
      DA_vehical_no: "BR1Q19955",
      retailer_id: "R03",
      paid_amount: "99",
      assigned_to: "swiggy",
      retailer_name: "Raju",
      date_and_time: "01/02/2020"
    },
  ]
}

export default orders